version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - '4000:4444'
    restart: on-failure
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'
  postgres:
    container_name: postgres
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    restart: always
